# Appveyor configuration file

# Suggested by https://github.com/kf6kjg in https://github.com/luca-piccioni/OpenGL.Net/issues/44; great idea
init:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { $env:TAG_VERSION = "$env:APPVEYOR_REPO_TAG_NAME" } else { $env:TAG_VERSION = "v0.5.0.$env:APPVEYOR_BUILD_NUMBER-alpha" }
  - ps: $env:TAG_VERSION = $env:TAG_VERSION -replace 'v',''
  - ps: Write-Host "Setting version to '$env:TAG_VERSION'"
  - ps: Update-AppveyorBuild -Version "$env:TAG_VERSION"

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      SLN_PATH: OpenGL.Net.sln
      SLN_BUILD_OPTS: /nologo /verbosity:quiet /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
      PUBLISH_NUGET: true

pull_requests:
  do_not_increment_build_number: true

matrix:
  fast_finish: false

skip_commits:
  message: /Update README.md/

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - cmd: dotnet restore $SLN_PATH

build_script:
  - cmd: msbuild $SLN_PATH $SLN_BUILD_OPTS /p:Configuration=Release /p:Platform="Any CPU"
after_build:
  - cmd: dotnet pack $SLN_PATH $SLN_BUILD_OPTS /p:Configuration=Release /p:Platform="Any CPU"

test: off

artifacts:
  - path: 'nuget/*.nupkg'
  - name: NuGet

deploy:
  - provider: NuGet
    name: nuget_release
    api_key:
      secure: hsqF28ceXmiIE0aa6mNKtvNJJuvRx0wRbbj7M8I9UiktTv8m3pjq5LCJpdAKYuPY
    skip_symbols: true
    on:
      appveyor_repo_tag: true

nuget:
    disable_publish_on_pr: true
