language: csharp
mono:
  - 5.4.1
solution: OpenGL.Net_Mono.sln
addons:
  apt:
     packages:
        - xserver-xorg-video-dummy
        - xpra
        - mesa-utils
install:
  - sudo nuget update -self
  - sudo nuget restore OpenGL.Net_Mono.sln
  - sudo nuget restore OpenGL.Net_VC14.sln
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 6 # give xvfb some time to start
script:
  - mono --version
  - xbuild /p:Configuration=Release OpenGL.Net_Mono.sln
  - glxinfo
after_script:
  - mono --debug --profile=log:coverage,covfilter=+OpenGL,covfilter=-OpenGL.Tests "packages/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe" "OpenGL.Net.Test/bin/net461/Release/OpenGL.Net.Test.dll"
  - mprof-report --reports=coverage --coverage-out=coverage.xml output.mlpd
  - bash <(curl -s https://codecov.io/bash) -F net461_Linux
